// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zapatitos.Infrastructure.Persistence;

#nullable disable

namespace Zapatitos.Infrastructure.Migrations
{
    [DbContext(typeof(ZapatitosDbContext))]
    [Migration("20260505202818_UpdatePaqueteServicioWithQuantity")]
    partial class UpdatePaqueteServicioWithQuantity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zapatitos.Domain.Entities.ArticuloInventario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("ControlarStock")
                        .HasColumnType("boolean")
                        .HasColumnName("controlar_stock");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioCosto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_costo");

                    b.Property<long?>("ProveedorId")
                        .HasColumnType("bigint")
                        .HasColumnName("proveedor_id");

                    b.Property<int>("StockActual")
                        .HasColumnType("integer")
                        .HasColumnName("stock_actual");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("stock_minimo");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("text")
                        .HasColumnName("unidad_medida");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_articulos_inventario");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("ix_articulos_inventario_proveedor_id");

                    b.ToTable("articulos_inventario", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.AsignacionStaff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<long>("EmpleadoId")
                        .HasColumnType("bigint")
                        .HasColumnName("empleado_id");

                    b.Property<bool>("EsPagado")
                        .HasColumnType("boolean")
                        .HasColumnName("es_pagado");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<long?>("PagoNominaId")
                        .HasColumnType("bigint")
                        .HasColumnName("pago_nomina_id");

                    b.Property<string>("RolEnEvento")
                        .HasColumnType("text")
                        .HasColumnName("rol_en_evento");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_asignaciones_staff");

                    b.HasIndex("EmpleadoId")
                        .HasDatabaseName("ix_asignaciones_staff_empleado_id");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("ix_asignaciones_staff_evento_id");

                    b.HasIndex("PagoNominaId")
                        .HasDatabaseName("ix_asignaciones_staff_pago_nomina_id");

                    b.ToTable("asignaciones_staff", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.CategoriaFinanciera", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_categorias_financieras");

                    b.ToTable("categorias_financieras", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_clientes_usuario_id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.ConfiguracionWeb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_configuraciones_web");

                    b.ToTable("configuraciones_web", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.ConsumoExtra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<long>("EmpleadoId")
                        .HasColumnType("bigint")
                        .HasColumnName("empleado_id");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<decimal>("PrecioUnitarioMomento")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario_momento");

                    b.Property<long>("ServicioId")
                        .HasColumnType("bigint")
                        .HasColumnName("servicio_id");

                    b.Property<decimal>("TotalConsumo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_consumo");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_consumos_extras");

                    b.HasIndex("EmpleadoId")
                        .HasDatabaseName("ix_consumos_extras_empleado_id");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("ix_consumos_extras_evento_id");

                    b.HasIndex("ServicioId")
                        .HasDatabaseName("ix_consumos_extras_servicio_id");

                    b.ToTable("consumos_extras", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Cumpleanero", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("EdadCumplir")
                        .HasColumnType("integer")
                        .HasColumnName("edad_cumplir");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<long>("NinoId")
                        .HasColumnType("bigint")
                        .HasColumnName("nino_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_evento_cumpleaneros");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("ix_evento_cumpleaneros_evento_id");

                    b.HasIndex("NinoId")
                        .HasDatabaseName("ix_evento_cumpleaneros_nino_id");

                    b.ToTable("evento_cumpleaneros", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.DisponibilidadConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer")
                        .HasColumnName("dia_semana");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicio");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("NombreBloque")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_bloque");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_disponibilidad_config");

                    b.ToTable("disponibilidad_config", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Empleado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<decimal>("PagoPorEvento")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pago_por_evento");

                    b.Property<string>("Puesto")
                        .HasColumnType("text")
                        .HasColumnName("puesto");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_empleados");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_empleados_usuario_id");

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Evento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CantidadNinosEstimada")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_ninos_estimada");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_evento");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicio");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("NotasAdmin")
                        .HasColumnType("text")
                        .HasColumnName("notas_admin");

                    b.Property<long>("PaqueteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paquete_id");

                    b.Property<decimal>("PrecioTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_total");

                    b.Property<decimal>("SaldoPendiente")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("saldo_pendiente");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_eventos");

                    b.HasIndex("PaqueteId")
                        .HasDatabaseName("ix_eventos_paquete_id");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.EventoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ArticuloId")
                        .HasColumnType("bigint")
                        .HasColumnName("articulo_id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<bool>("EsIncluidoEnPaquete")
                        .HasColumnType("boolean")
                        .HasColumnName("es_incluido_en_paquete");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<long?>("ServicioId")
                        .HasColumnType("bigint")
                        .HasColumnName("servicio_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_evento_items");

                    b.HasIndex("ArticuloId")
                        .HasDatabaseName("ix_evento_items_articulo_id");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("ix_evento_items_evento_id");

                    b.HasIndex("ServicioId")
                        .HasDatabaseName("ix_evento_items_servicio_id");

                    b.ToTable("evento_items", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.FotoEvento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<bool>("VisibleParaCliente")
                        .HasColumnType("boolean")
                        .HasColumnName("visible_para_cliente");

                    b.HasKey("Id")
                        .HasName("pk_foto_evento");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("ix_foto_evento_evento_id");

                    b.ToTable("foto_evento", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Gasto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoria_id");

                    b.Property<string>("ComprobanteUrl")
                        .HasColumnType("text")
                        .HasColumnName("comprobante_url");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_gastos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_gastos_categoria_id");

                    b.ToTable("gastos", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.InvitacionDigital", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<Guid>("TokenAcceso")
                        .HasColumnType("uuid")
                        .HasColumnName("token_acceso");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_invitaciones_digitales");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("ix_invitaciones_digitales_evento_id");

                    b.ToTable("invitaciones_digitales", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.MetodoPago", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_metodos_pago");

                    b.ToTable("metodos_pago", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.MovimientoCaja", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concepto");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto");

                    b.Property<long?>("ReferenciaId")
                        .HasColumnType("bigint")
                        .HasColumnName("referencia_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_movimientos_caja");

                    b.ToTable("movimientos_caja", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Nino", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_ninos");

                    b.ToTable("ninos", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Pago", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ComprobanteUrl")
                        .HasColumnType("text")
                        .HasColumnName("comprobante_url");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<long?>("MetodoPagoId")
                        .HasColumnType("bigint")
                        .HasColumnName("metodo_pago_id");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Referencia")
                        .HasColumnType("text")
                        .HasColumnName("referencia");

                    b.Property<long?>("VerificadoPorId")
                        .HasColumnType("bigint")
                        .HasColumnName("verificado_por");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_pagos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_pagos_cliente_id");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("ix_pagos_evento_id");

                    b.HasIndex("MetodoPagoId")
                        .HasDatabaseName("ix_pagos_metodo_pago_id");

                    b.HasIndex("VerificadoPorId")
                        .HasDatabaseName("ix_pagos_verificado_por_id");

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.PagoNomina", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<long>("EmpleadoId")
                        .HasColumnType("bigint")
                        .HasColumnName("empleado_id");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Periodo")
                        .HasColumnType("text")
                        .HasColumnName("periodo");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_nominas");

                    b.HasIndex("EmpleadoId")
                        .HasDatabaseName("ix_nominas_empleado_id");

                    b.ToTable("nominas", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Paquete", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CapacidadNinos")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_ninos");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("descuento");

                    b.Property<int>("DuracionHoras")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_horas");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_base");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_paquetes");

                    b.ToTable("paquetes", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.PaqueteArticulo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ArticuloId")
                        .HasColumnType("bigint")
                        .HasColumnName("articulo_id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<long>("PaqueteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paquete_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_paquetes_articulos");

                    b.HasIndex("ArticuloId")
                        .HasDatabaseName("ix_paquetes_articulos_articulo_id");

                    b.HasIndex("PaqueteId")
                        .HasDatabaseName("ix_paquetes_articulos_paquete_id");

                    b.ToTable("paquetes_articulos", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.PaqueteServicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<long>("PaqueteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paquete_id");

                    b.Property<long>("ServicioId")
                        .HasColumnType("bigint")
                        .HasColumnName("servicio_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_paquetes_servicios");

                    b.HasIndex("PaqueteId")
                        .HasDatabaseName("ix_paquetes_servicios_paquete_id");

                    b.HasIndex("ServicioId")
                        .HasDatabaseName("ix_paquetes_servicios_servicio_id");

                    b.ToTable("paquetes_servicios", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Permiso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_permisos");

                    b.ToTable("permisos", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.ProductoProduccion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CantidadProducida")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_producida");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("text")
                        .HasColumnName("unidad_medida");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_produccion_productos");

                    b.ToTable("produccion_productos", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Proveedor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContactoNombre")
                        .HasColumnType("text")
                        .HasColumnName("contacto_nombre");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_proveedores");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.RecetaIngrediente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ArticuloInventarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("articulo_inventario_id");

                    b.Property<decimal>("CantidadRequerida")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cantidad_requerida");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<long>("ProductoProduccionId")
                        .HasColumnType("bigint")
                        .HasColumnName("producto_produccion_id");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("text")
                        .HasColumnName("unidad_medida");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_receta_ingredientes");

                    b.HasIndex("ArticuloInventarioId")
                        .HasDatabaseName("ix_receta_ingredientes_articulo_inventario_id");

                    b.HasIndex("ProductoProduccionId")
                        .HasDatabaseName("ix_receta_ingredientes_producto_produccion_id");

                    b.ToTable("receta_ingredientes", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.RetroalimentacionCliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CalificacionGeneral")
                        .HasColumnType("integer")
                        .HasColumnName("calificacion_general");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_retroalimentacion_cliente");

                    b.HasIndex("EventoId")
                        .IsUnique()
                        .HasDatabaseName("ix_retroalimentacion_cliente_evento_id");

                    b.ToTable("retroalimentacion_cliente", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Servicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ArticuloInventarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("articulo_inventario_id");

                    b.Property<int>("CantidadMinima")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_minima");

                    b.Property<decimal>("CostoBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_base");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<bool>("EsExtra")
                        .HasColumnType("boolean")
                        .HasColumnName("es_extra");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioProveedor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_proveedor");

                    b.Property<long?>("ProductoProduccionId")
                        .HasColumnType("bigint")
                        .HasColumnName("producto_produccion_id");

                    b.Property<long?>("ProveedorId")
                        .HasColumnType("bigint")
                        .HasColumnName("proveedor_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_servicios");

                    b.HasIndex("ArticuloInventarioId")
                        .HasDatabaseName("ix_servicios_articulo_inventario_id");

                    b.HasIndex("ProductoProduccionId")
                        .HasDatabaseName("ix_servicios_producto_produccion_id");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("ix_servicios_proveedor_id");

                    b.ToTable("servicios", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.TareaOperativa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AsignadoAId")
                        .HasColumnType("bigint")
                        .HasColumnName("asignado_a");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_completada");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("NombreTarea")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_tarea");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tareas_operativas");

                    b.HasIndex("AsignadoAId")
                        .HasDatabaseName("ix_tareas_operativas_asignado_a_id");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("ix_tareas_operativas_evento_id");

                    b.ToTable("tareas_operativas", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modificado_en");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UltimaConexion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ultima_conexion");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("eventos_clientes", b =>
                {
                    b.Property<long>("cliente_id")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long>("evento_id")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.HasKey("cliente_id", "evento_id")
                        .HasName("pk_eventos_clientes");

                    b.HasIndex("evento_id")
                        .HasDatabaseName("ix_eventos_clientes_evento_id");

                    b.ToTable("eventos_clientes", (string)null);
                });

            modelBuilder.Entity("ninos_clientes", b =>
                {
                    b.Property<long>("cliente_id")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long>("nino_id")
                        .HasColumnType("bigint")
                        .HasColumnName("nino_id");

                    b.HasKey("cliente_id", "nino_id")
                        .HasName("pk_ninos_clientes");

                    b.HasIndex("nino_id")
                        .HasDatabaseName("ix_ninos_clientes_nino_id");

                    b.ToTable("ninos_clientes", (string)null);
                });

            modelBuilder.Entity("roles_permisos", b =>
                {
                    b.Property<long>("permiso_id")
                        .HasColumnType("bigint")
                        .HasColumnName("permiso_id");

                    b.Property<long>("rol_id")
                        .HasColumnType("bigint")
                        .HasColumnName("rol_id");

                    b.HasKey("permiso_id", "rol_id")
                        .HasName("pk_roles_permisos");

                    b.HasIndex("rol_id")
                        .HasDatabaseName("ix_roles_permisos_rol_id");

                    b.ToTable("roles_permisos", (string)null);
                });

            modelBuilder.Entity("usuarios_roles", b =>
                {
                    b.Property<long>("rol_id")
                        .HasColumnType("bigint")
                        .HasColumnName("rol_id");

                    b.Property<long>("usuario_id")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("rol_id", "usuario_id")
                        .HasName("pk_usuarios_roles");

                    b.HasIndex("usuario_id")
                        .HasDatabaseName("ix_usuarios_roles_usuario_id");

                    b.ToTable("usuarios_roles", (string)null);
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.ArticuloInventario", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("Articulos")
                        .HasForeignKey("ProveedorId")
                        .HasConstraintName("fk_articulos_inventario_proveedores_proveedor_id");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.AsignacionStaff", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asignaciones_staff_empleados_empleado_id");

                    b.HasOne("Zapatitos.Domain.Entities.Evento", "Evento")
                        .WithMany("Staff")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asignaciones_staff_eventos_evento_id");

                    b.HasOne("Zapatitos.Domain.Entities.PagoNomina", "PagoNomina")
                        .WithMany()
                        .HasForeignKey("PagoNominaId")
                        .HasConstraintName("fk_asignaciones_staff_nominas_pago_nomina_id");

                    b.Navigation("Empleado");

                    b.Navigation("Evento");

                    b.Navigation("PagoNomina");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("fk_clientes_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.ConsumoExtra", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consumos_extras_empleados_empleado_id");

                    b.HasOne("Zapatitos.Domain.Entities.Evento", "Evento")
                        .WithMany("ConsumosExtras")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consumos_extras_eventos_evento_id");

                    b.HasOne("Zapatitos.Domain.Entities.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consumos_extras_servicios_servicio_id");

                    b.Navigation("Empleado");

                    b.Navigation("Evento");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Cumpleanero", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Evento", "Evento")
                        .WithMany("Cumpleaneros")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evento_cumpleaneros_eventos_evento_id");

                    b.HasOne("Zapatitos.Domain.Entities.Nino", "Nino")
                        .WithMany("ParticipacionesCumpleanos")
                        .HasForeignKey("NinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evento_cumpleaneros_ninos_nino_id");

                    b.Navigation("Evento");

                    b.Navigation("Nino");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_empleados_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Evento", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Paquete", "Paquete")
                        .WithMany()
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_paquetes_paquete_id");

                    b.Navigation("Paquete");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.EventoItem", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.ArticuloInventario", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId")
                        .HasConstraintName("fk_evento_items_articulos_inventario_articulo_id");

                    b.HasOne("Zapatitos.Domain.Entities.Evento", "Evento")
                        .WithMany("Items")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evento_items_eventos_evento_id");

                    b.HasOne("Zapatitos.Domain.Entities.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .HasConstraintName("fk_evento_items_servicios_servicio_id");

                    b.Navigation("Articulo");

                    b.Navigation("Evento");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.FotoEvento", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Evento", "Evento")
                        .WithMany("Fotos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_foto_evento_eventos_evento_id");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Gasto", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.CategoriaFinanciera", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gastos_categorias_financieras_categoria_id");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.InvitacionDigital", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitaciones_digitales_eventos_evento_id");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Pago", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("fk_pagos_clientes_cliente_id");

                    b.HasOne("Zapatitos.Domain.Entities.Evento", "Evento")
                        .WithMany("Pagos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_eventos_evento_id");

                    b.HasOne("Zapatitos.Domain.Entities.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .HasConstraintName("fk_pagos_metodos_pago_metodo_pago_id");

                    b.HasOne("Zapatitos.Domain.Entities.Empleado", "VerificadoPor")
                        .WithMany()
                        .HasForeignKey("VerificadoPorId")
                        .HasConstraintName("fk_pagos_empleados_verificado_por_id");

                    b.Navigation("Cliente");

                    b.Navigation("Evento");

                    b.Navigation("MetodoPago");

                    b.Navigation("VerificadoPor");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.PagoNomina", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nominas_empleados_empleado_id");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.PaqueteArticulo", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.ArticuloInventario", "Articulo")
                        .WithMany("PaquetesDondeSeUsa")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paquetes_articulos_articulos_inventario_articulo_id");

                    b.HasOne("Zapatitos.Domain.Entities.Paquete", "Paquete")
                        .WithMany("Articulos")
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paquetes_articulos_paquetes_paquete_id");

                    b.Navigation("Articulo");

                    b.Navigation("Paquete");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.PaqueteServicio", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Paquete", "Paquete")
                        .WithMany("Servicios")
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paquetes_servicios_paquetes_paquete_id");

                    b.HasOne("Zapatitos.Domain.Entities.Servicio", "Servicio")
                        .WithMany("Paquetes")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paquetes_servicios_servicios_servicio_id");

                    b.Navigation("Paquete");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.RecetaIngrediente", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.ArticuloInventario", "Articulo")
                        .WithMany("UsadoEnRecetas")
                        .HasForeignKey("ArticuloInventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receta_ingredientes_articulos_inventario_articulo_inventari");

                    b.HasOne("Zapatitos.Domain.Entities.ProductoProduccion", "Producto")
                        .WithMany("Ingredientes")
                        .HasForeignKey("ProductoProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receta_ingredientes_productos_produccion_producto_produccio");

                    b.Navigation("Articulo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.RetroalimentacionCliente", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Evento", "Evento")
                        .WithOne("Retroalimentacion")
                        .HasForeignKey("Zapatitos.Domain.Entities.RetroalimentacionCliente", "EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retroalimentacion_cliente_eventos_evento_id");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Servicio", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.ArticuloInventario", "ArticuloInventario")
                        .WithMany()
                        .HasForeignKey("ArticuloInventarioId")
                        .HasConstraintName("fk_servicios_articulos_inventario_articulo_inventario_id");

                    b.HasOne("Zapatitos.Domain.Entities.ProductoProduccion", "ProductoProduccion")
                        .WithMany("Servicios")
                        .HasForeignKey("ProductoProduccionId")
                        .HasConstraintName("fk_servicios_productos_produccion_producto_produccion_id");

                    b.HasOne("Zapatitos.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .HasConstraintName("fk_servicios_proveedores_proveedor_id");

                    b.Navigation("ArticuloInventario");

                    b.Navigation("ProductoProduccion");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.TareaOperativa", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Empleado", "AsignadoA")
                        .WithMany()
                        .HasForeignKey("AsignadoAId")
                        .HasConstraintName("fk_tareas_operativas_empleados_asignado_a_id");

                    b.HasOne("Zapatitos.Domain.Entities.Evento", "Evento")
                        .WithMany("Tareas")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tareas_operativas_eventos_evento_id");

                    b.Navigation("AsignadoA");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("eventos_clientes", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("cliente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_clientes_clientes_cliente_id");

                    b.HasOne("Zapatitos.Domain.Entities.Evento", null)
                        .WithMany()
                        .HasForeignKey("evento_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_clientes_eventos_evento_id");
                });

            modelBuilder.Entity("ninos_clientes", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("cliente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ninos_clientes_clientes_cliente_id");

                    b.HasOne("Zapatitos.Domain.Entities.Nino", null)
                        .WithMany()
                        .HasForeignKey("nino_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ninos_clientes_ninos_nino_id");
                });

            modelBuilder.Entity("roles_permisos", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Permiso", null)
                        .WithMany()
                        .HasForeignKey("permiso_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permisos_permisos_permiso_id");

                    b.HasOne("Zapatitos.Domain.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("rol_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_permisos_roles_rol_id");
                });

            modelBuilder.Entity("usuarios_roles", b =>
                {
                    b.HasOne("Zapatitos.Domain.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("rol_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_roles_rol_id");

                    b.HasOne("Zapatitos.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_usuarios_usuario_id");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.ArticuloInventario", b =>
                {
                    b.Navigation("PaquetesDondeSeUsa");

                    b.Navigation("UsadoEnRecetas");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Evento", b =>
                {
                    b.Navigation("ConsumosExtras");

                    b.Navigation("Cumpleaneros");

                    b.Navigation("Fotos");

                    b.Navigation("Items");

                    b.Navigation("Pagos");

                    b.Navigation("Retroalimentacion");

                    b.Navigation("Staff");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Nino", b =>
                {
                    b.Navigation("ParticipacionesCumpleanos");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Paquete", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.ProductoProduccion", b =>
                {
                    b.Navigation("Ingredientes");

                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("Zapatitos.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("Paquetes");
                });
#pragma warning restore 612, 618
        }
    }
}
